[project]
name = 'Smart-City-Infrastructure-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-registration]
path = 'contracts/asset-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-scheduling]
path = 'contracts/maintenance-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-analytics]
path = 'contracts/performance-analytics.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-allocation]
path = 'contracts/resource-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-network]
path = 'contracts/sensor-network.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
